// <auto-generated />
using System;
using MDMS_Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MDMS_Backend.Migrations
{
    [DbContext(typeof(MdmsDbContext))]
    partial class MdmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MDMS_Backend.Models.Consumer", b =>
                {
                    b.Property<int>("ConsumerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConsumerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsumerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ConsumerId")
                        .HasName("PK__Consumer__63BBE99A874A2B45");

                    b.HasIndex("StatusId");

                    b.ToTable("Consumers");
                });

            modelBuilder.Entity("MDMS_Backend.Models.Dtr", b =>
                {
                    b.Property<int>("Dtrid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DTRID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Dtrid"));

                    b.Property<string>("Dtrname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DTRName");

                    b.Property<int>("FeederId")
                        .HasColumnType("int")
                        .HasColumnName("FeederID");

                    b.HasKey("Dtrid")
                        .HasName("PK__DTRs__F865635FADB6DCC5");

                    b.HasIndex("FeederId");

                    b.HasIndex(new[] { "Dtrname" }, "UQ__DTRs__263F444BB115D569")
                        .IsUnique();

                    b.ToTable("DTRs", (string)null);
                });

            modelBuilder.Entity("MDMS_Backend.Models.Feeder", b =>
                {
                    b.Property<int>("FeederId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FeederID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeederId"));

                    b.Property<string>("FeederName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SubstationId")
                        .HasColumnType("int")
                        .HasColumnName("SubstationID");

                    b.HasKey("FeederId")
                        .HasName("PK__Feeders__9B20B0FCC20F2522");

                    b.HasIndex("SubstationId");

                    b.HasIndex(new[] { "FeederName" }, "UQ__Feeders__FB00FBD9938761C9")
                        .IsUnique();

                    b.ToTable("Feeders");
                });

            modelBuilder.Entity("MDMS_Backend.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ManufacturerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManufacturerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ManufacturerId")
                        .HasName("PK__Manufact__357E5CA1D5BD4EDC");

                    b.HasIndex(new[] { "Name" }, "UQ__Manufact__737584F6F5BBDD81")
                        .IsUnique();

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("MDMS_Backend.Models.Meter", b =>
                {
                    b.Property<int>("MeterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MeterID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeterId"));

                    b.Property<int>("ConsumerId")
                        .HasColumnType("int")
                        .HasColumnName("ConsumerID");

                    b.Property<int>("Dtrid")
                        .HasColumnType("int")
                        .HasColumnName("DTRID");

                    b.Property<string>("Firmware")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Iccid")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ICCID");

                    b.Property<string>("Imsi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("IMSI");

                    b.Property<DateOnly>("InstallDate")
                        .HasColumnType("date");

                    b.Property<string>("Ipaddress")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("IPAddress");

                    b.Property<decimal>("LatestReading")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int")
                        .HasColumnName("ManufacturerID");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<int>("TariffId")
                        .HasColumnType("int")
                        .HasColumnName("TariffID");

                    b.HasKey("MeterId")
                        .HasName("PK__Meters__59223B8C0448709E");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("Dtrid");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TariffId");

                    b.ToTable("Meters");
                });

            modelBuilder.Entity("MDMS_Backend.Models.MonthlyBill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BillID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillId"));

                    b.Property<decimal>("BaseRate")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("BillStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("BillingMonth")
                        .HasColumnType("date");

                    b.Property<int>("ConsumerId")
                        .HasColumnType("int")
                        .HasColumnName("ConsumerID");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MeterId")
                        .HasColumnType("int")
                        .HasColumnName("MeterID");

                    b.Property<decimal>("MonthlyReadingKwh")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("TariffName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TotalBill")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("BillId")
                        .HasName("PK__MonthlyB__11F2FC4A0301E136");

                    b.HasIndex("MeterId");

                    b.ToTable("MonthlyBills");
                });

            modelBuilder.Entity("MDMS_Backend.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3A6C41C934");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B61605D26D555")
                        .IsUnique();

                    b.HasIndex(new[] { "Abbreviation" }, "UQ__Roles__9C41170EA06E4C1A")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MDMS_Backend.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StatusId")
                        .HasName("PK__Statuses__C8EE2043B2F0D9A7");

                    b.HasIndex(new[] { "Name" }, "UQ__Statuses__737584F6A0CBD582")
                        .IsUnique();

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("MDMS_Backend.Models.Substation", b =>
                {
                    b.Property<int>("SubstationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubstationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubstationId"));

                    b.Property<string>("SubstationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int")
                        .HasColumnName("ZoneID");

                    b.HasKey("SubstationId")
                        .HasName("PK__Substati__BB479C6F4C9F78BD");

                    b.HasIndex("ZoneId");

                    b.HasIndex(new[] { "SubstationName" }, "UQ__Substati__32F7515900B0DA0D")
                        .IsUnique();

                    b.ToTable("Substations");
                });

            modelBuilder.Entity("MDMS_Backend.Models.Tariff", b =>
                {
                    b.Property<int>("TariffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TariffID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TariffId"));

                    b.Property<decimal>("BaseRate")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("TariffId")
                        .HasName("PK__Tariffs__EBAF9D931C1E783F");

                    b.ToTable("Tariffs");
                });

            modelBuilder.Entity("MDMS_Backend.Models.TariffSlab", b =>
                {
                    b.Property<int>("SlabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SlabID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlabId"));

                    b.Property<decimal>("FromKwh")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("FromKWh");

                    b.Property<decimal>("RatePerKwh")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("RatePerKWh");

                    b.Property<int>("TariffId")
                        .HasColumnType("int")
                        .HasColumnName("TariffID");

                    b.Property<decimal>("ToKwh")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("ToKWh");

                    b.HasKey("SlabId")
                        .HasName("PK__TariffSl__D61699010C08E430");

                    b.HasIndex("TariffId");

                    b.ToTable("TariffSlabs");
                });

            modelBuilder.Entity("MDMS_Backend.Models.User", b =>
                {
                    b.Property<int>("UserNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserNumber"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime");

                    b.Property<byte[]>("PasswordHashed")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varbinary(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("UserId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("UserID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserNumber");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "UserId" }, "UQ_UserID")
                        .IsUnique()
                        .HasFilter("[UserID] IS NOT NULL");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105349FC0BA7D")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasTrigger("trg_GenerateUserIDs");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("MDMS_Backend.Models.Zone", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ZoneID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZoneId"));

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ZoneId")
                        .HasName("PK__Zones__601667953329FE7E");

                    b.HasIndex(new[] { "ZoneName" }, "UQ__Zones__EE0DD16841D70E1E")
                        .IsUnique();

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("MDMS_Backend.Models.Consumer", b =>
                {
                    b.HasOne("MDMS_Backend.Models.Status", "Status")
                        .WithMany("Consumers")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Consumers_Statuses");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MDMS_Backend.Models.Dtr", b =>
                {
                    b.HasOne("MDMS_Backend.Models.Feeder", "Feeder")
                        .WithMany("Dtrs")
                        .HasForeignKey("FeederId")
                        .IsRequired()
                        .HasConstraintName("FK_DTRs_Feeders");

                    b.Navigation("Feeder");
                });

            modelBuilder.Entity("MDMS_Backend.Models.Feeder", b =>
                {
                    b.HasOne("MDMS_Backend.Models.Substation", "Substation")
                        .WithMany("Feeders")
                        .HasForeignKey("SubstationId")
                        .IsRequired()
                        .HasConstraintName("FK_Feeders_Substations");

                    b.Navigation("Substation");
                });

            modelBuilder.Entity("MDMS_Backend.Models.Meter", b =>
                {
                    b.HasOne("MDMS_Backend.Models.Consumer", "Consumer")
                        .WithMany("Meters")
                        .HasForeignKey("ConsumerId")
                        .IsRequired()
                        .HasConstraintName("FK_Meters_Consumers");

                    b.HasOne("MDMS_Backend.Models.Dtr", "Dtr")
                        .WithMany("Meters")
                        .HasForeignKey("Dtrid")
                        .IsRequired()
                        .HasConstraintName("FK_Meters_DTRs");

                    b.HasOne("MDMS_Backend.Models.Manufacturer", "Manufacturer")
                        .WithMany("Meters")
                        .HasForeignKey("ManufacturerId")
                        .IsRequired()
                        .HasConstraintName("FK_Meters_Manufacturers");

                    b.HasOne("MDMS_Backend.Models.Status", "Status")
                        .WithMany("Meters")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Meters_Statuses");

                    b.HasOne("MDMS_Backend.Models.Tariff", "Tariff")
                        .WithMany("Meters")
                        .HasForeignKey("TariffId")
                        .IsRequired()
                        .HasConstraintName("FK_Meters_Tariffs");

                    b.Navigation("Consumer");

                    b.Navigation("Dtr");

                    b.Navigation("Manufacturer");

                    b.Navigation("Status");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("MDMS_Backend.Models.MonthlyBill", b =>
                {
                    b.HasOne("MDMS_Backend.Models.Meter", "Meter")
                        .WithMany("MonthlyBills")
                        .HasForeignKey("MeterId")
                        .IsRequired()
                        .HasConstraintName("FK_MonthlyBills_Meters");

                    b.Navigation("Meter");
                });

            modelBuilder.Entity("MDMS_Backend.Models.Substation", b =>
                {
                    b.HasOne("MDMS_Backend.Models.Zone", "Zone")
                        .WithMany("Substations")
                        .HasForeignKey("ZoneId")
                        .IsRequired()
                        .HasConstraintName("FK_Substations_Zones");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("MDMS_Backend.Models.TariffSlab", b =>
                {
                    b.HasOne("MDMS_Backend.Models.Tariff", "Tariff")
                        .WithMany("TariffSlabs")
                        .HasForeignKey("TariffId")
                        .IsRequired()
                        .HasConstraintName("FK_TariffSlabs_Tariffs");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("MDMS_Backend.Models.User", b =>
                {
                    b.HasOne("MDMS_Backend.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MDMS_Backend.Models.Consumer", b =>
                {
                    b.Navigation("Meters");
                });

            modelBuilder.Entity("MDMS_Backend.Models.Dtr", b =>
                {
                    b.Navigation("Meters");
                });

            modelBuilder.Entity("MDMS_Backend.Models.Feeder", b =>
                {
                    b.Navigation("Dtrs");
                });

            modelBuilder.Entity("MDMS_Backend.Models.Manufacturer", b =>
                {
                    b.Navigation("Meters");
                });

            modelBuilder.Entity("MDMS_Backend.Models.Meter", b =>
                {
                    b.Navigation("MonthlyBills");
                });

            modelBuilder.Entity("MDMS_Backend.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MDMS_Backend.Models.Status", b =>
                {
                    b.Navigation("Consumers");

                    b.Navigation("Meters");
                });

            modelBuilder.Entity("MDMS_Backend.Models.Substation", b =>
                {
                    b.Navigation("Feeders");
                });

            modelBuilder.Entity("MDMS_Backend.Models.Tariff", b =>
                {
                    b.Navigation("Meters");

                    b.Navigation("TariffSlabs");
                });

            modelBuilder.Entity("MDMS_Backend.Models.Zone", b =>
                {
                    b.Navigation("Substations");
                });
#pragma warning restore 612, 618
        }
    }
}
